//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWN.TTR.RolesServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://swn.com/ICC/ODS/RolesService", ConfigurationName="RolesServices.RolesServiceSoap")]
    public interface RolesServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://swn.com/ICC/ODS/RolesService/GetRolesForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] GetRolesForUser(string user, string system, string subsystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://swn.com/ICC/ODS/RolesService/GetUsersInRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] GetUsersInRole(string role, string system, string subsystem);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RolesServiceSoapChannel : SWN.TTR.RolesServices.RolesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RolesServiceSoapClient : System.ServiceModel.ClientBase<SWN.TTR.RolesServices.RolesServiceSoap>, SWN.TTR.RolesServices.RolesServiceSoap {
        
        public RolesServiceSoapClient() {
        }
        
        public RolesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RolesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetRolesForUser(string user, string system, string subsystem) {
            return base.Channel.GetRolesForUser(user, system, subsystem);
        }
        
        public string[] GetUsersInRole(string role, string system, string subsystem) {
            return base.Channel.GetUsersInRole(role, system, subsystem);
        }
    }
}
