//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWN.TTR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWN.TTR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request cannot be approved since it is no longer pending your approval..
        /// </summary>
        internal static string ApproveNotAllowedException {
            get {
                return ResourceManager.GetString("ApproveNotAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to approve this request..
        /// </summary>
        internal static string ApproveNotAuthorizedException {
            get {
                return ResourceManager.GetString("ApproveNotAuthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments are required before denying a request..
        /// </summary>
        internal static string CommentsMissingForDenyException {
            get {
                return ResourceManager.GetString("CommentsMissingForDenyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {2} must be greater than or equal to today&apos;s date..
        /// </summary>
        internal static string DateGreaterEqualThanTodayMessage {
            get {
                return ResourceManager.GetString("DateGreaterEqualThanTodayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this request.  The request was not requested by you and it is not in a New status..
        /// </summary>
        internal static string DeleteNotAllowedException {
            get {
                return ResourceManager.GetString("DeleteNotAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to delete this request..
        /// </summary>
        internal static string DeleteNotAuthorizedException {
            get {
                return ResourceManager.GetString("DeleteNotAuthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request cannot be denied since it is no longer pending your approval..
        /// </summary>
        internal static string DenyNotAllowedException {
            get {
                return ResourceManager.GetString("DenyNotAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to deny this request..
        /// </summary>
        internal static string DenyNotAuthorizedException {
            get {
                return ResourceManager.GetString("DenyNotAuthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {2} must be greater than or equal to the start date..
        /// </summary>
        internal static string EndDateInvalidMessage {
            get {
                return ResourceManager.GetString("EndDateInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request cannot be approved since it is no longer pending your approval..
        /// </summary>
        internal static string FinalApproveNotAllowedException {
            get {
                return ResourceManager.GetString("FinalApproveNotAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to approve this request..
        /// </summary>
        internal static string FinalApproveNotAuthorizedException {
            get {
                return ResourceManager.GetString("FinalApproveNotAuthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {2} must be between {3} and {5}..
        /// </summary>
        internal static string InvalidDateRangeMessage {
            get {
                return ResourceManager.GetString("InvalidDateRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {2} must be between {3} and {5} characters long..
        /// </summary>
        internal static string InvalidStringLengthMessage {
            get {
                return ResourceManager.GetString("InvalidStringLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body,table {{font-family:Arial;font-size:10pt;}}
        ///        #content {{ padding: 4px; }}
        ///        .message {{margin: 4px 0px 4px 0px;}}
        ///        .label {{font-weight:bold;color:Navy;text-align:left;width:150px;border-right:solid 1px Gray;font-size:9pt;}}
        ///        div.header {{bac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestActedOnEmail {
            get {
                return ResourceManager.GetString("RequestActedOnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Training and Travel Request Has Been {0}.
        /// </summary>
        internal static string RequestActedOnSubject {
            get {
                return ResourceManager.GetString("RequestActedOnSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Training and Travel Request Requires Your Review.
        /// </summary>
        internal static string RequestReviewalEmailSubject {
            get {
                return ResourceManager.GetString("RequestReviewalEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {2} is required..
        /// </summary>
        internal static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body,table {{font-family:Arial;font-size:10pt;}}
        ///        #content {{ padding: 4px; }}
        ///        .message {{margin: 4px 0px 4px 0px;}}
        ///        .label {{font-weight:bold;color:Navy;text-align:left;width:150px;border-right:solid 1px Gray;font-size:9pt;}}
        ///        div.header {{bac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReviewRequestEmail {
            get {
                return ResourceManager.GetString("ReviewRequestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routed to {0}..
        /// </summary>
        internal static string RoutedComment {
            get {
                return ResourceManager.GetString("RoutedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request cannot be routed since it has already been {0}..
        /// </summary>
        internal static string RouteNotAllowedException {
            get {
                return ResourceManager.GetString("RouteNotAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to route this request..
        /// </summary>
        internal static string RouteNotAuthorizedException {
            get {
                return ResourceManager.GetString("RouteNotAuthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot route a Pending request to a non-approver..
        /// </summary>
        internal static string RouteToNonApproverException {
            get {
                return ResourceManager.GetString("RouteToNonApproverException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot save this request..
        /// </summary>
        internal static string SaveNotAllowedException {
            get {
                return ResourceManager.GetString("SaveNotAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to save this request..
        /// </summary>
        internal static string SaveNotAuthorizedException {
            get {
                return ResourceManager.GetString("SaveNotAuthorizedException", resourceCulture);
            }
        }
    }
}
